### ISSUE TITLE
Add manifest to enforce start-up as admin

### ISSUE THREAD

**Issue by Fribur** [praydog/uevr-frontend#5]
I would assume most user start the framework as Standard Users, and not as Admin. While the current applications offers a "re-start as Admin", it is noticeable on discord that many users do not see that or do not know what this mean. Therefore I would suggest to enforce admin via a manifest: Within Visual Studio CTRL+Shift+A -->Application Manifest File --> `<requestedExecutionLevel  level="requireAdministrator" uiAccess="false" />`
[app.manifest.txt](https://github.com/praydog/uevr-frontend/files/13855887/app.manifest.txt)
![image](https://github.com/praydog/uevr-frontend/assets/16464641/a3ebf95b-1574-416d-b6aa-08c730e3f31a)

**Comment by keton** [comment]
can we please NOT do that:
1. default installations of pico streaming assistant, virtual desktop and steam link execute as regular user and won't be able to interact with resulting UAC prompt. For VD it can be fixed but not for others. You'd need to take your headset off, physically go to your PC and use mouse. Not ideal experience IMO.
2. this would break launcher flows. My homebrew launcher currently starts the game, waits 30s, starts UEVR frontend with `--attach` option. This automatically injects and focuses game window. I don't need to do anything. If elevation would be mandatory I'd need to take my headset off, confirm UAC and whole flow would be broken
3. I'm yet to see a game that requires elevation for injection. I've tried multiple games on 3 main launchers - Epic, Xbox and Steam. My guess is games requiring elevation are the exception here.
4. if you can do something as regular user you should

**Comment by Fribur** [comment]
Agree. I was under wrong impression the process list is only populated when launching as admin. Will close the issue.
